FROM python:3.11-slim

WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy project
COPY webapp/ /app/webapp
COPY src/ /app/src
COPY plugins/ /app/plugins

EXPOSE 8501

# Ensure Python can find src and plugins
ENV PYTHONPATH=/app:/app/src:/app/plugins

CMD ["python", "-m", "streamlit", "run", "/app/webapp/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
